import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Exo_2 } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const exo2 = Exo_2({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${exo2.className}`} >{children}</body>
    </html>
  )
}
